services:
  - type: web
    name: ems-backend
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build --workspace backend
    startCommand: npm run start --workspace backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
